<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <AssemblyName>KeyboardLayoutIndicator</AssemblyName>
    <RootNamespace>KeyboardLayoutIndicator</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Product>Keyboard Layout Indicator</Product>
    <AssemblyTitle>Keyboard Layout Indicator</AssemblyTitle>
    <Version>1.0.0</Version>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

</Project>
